# Generated by Django 4.2.30 on 2026-09-20 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_medicalreport_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalreport',
            name='ai_explanation',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='confidence',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='follow_up',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='medications',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/%d/'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('bio', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
