# Generated by Django 4.2.30 on 2026-09-11 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalreport',
            name='ai_explanation',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='confidence',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='follow_up',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='medications',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
