# Generated by Django 4.2.30 on 2026-09-26 12:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_populate_share_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalreport',
            name='share_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
